### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by ZuseZ4**

### CODE REVIEW

**Comment by samestep** [comment]
Thanks for documenting this! Currently on my machine this fails with the following error message:

```
error: the `-Z unstable-options` flag must also be passed to enable the flag `check-cfg`
error: the `-Z unstable-options` flag must also be passed to enable the flag `check-cfg`


error: could not compile `samples` (lib test)
warning: build failed, waiting for other jobs to finish...
error: could not compile `samples` (lib)
```

**Comment by ZuseZ4** [comment]
Yes, but that error should go away and the examples should compile if you pass the flag. I am not sure if it will be still needed once I rebased and the error message in this case at least is correct, so I didn't add it to the docs.

**Comment by samestep** [comment]
@ZuseZ4 so I should clean my Enzyme build and try again with the latest `main` and it will work?

**Comment by ZuseZ4** [comment]
No, the rebase is still work in progress. And I am not 100% sure if it will directly be sufficient to remove this error, I'll decide afterwards if I can get rid of it, or if I need to add it to the docs. This is the WIP rebase PR: https://github.com/EnzymeAD/rust/pull/162
For now I'd recommend to just set the flag, that will be less work. Also keep in mind that some of the docs changed recently, mainly https://enzyme.mit.edu/rust/Debugging.html#supported-rustflags

**Pull request merged**
