### PR TITLE
add tt to mem calls

### PR DESCRIPTION
**Pull request by ZuseZ4**
wip, but didn't break anything for me. Let's ask CI

### CODE REVIEW

**Comment by jedbrown** [comment]
Does anyone understand why the cache [is present](https://github.com/EnzymeAD/rust/actions/caches), but [not found](https://github.com/EnzymeAD/rust/actions/runs/8484325350/job/23247047361)?
image
```
Run actions/cache@v4
  with:
    path: build/build/x86_64-unknown-linux-gnu/llvm
    key: openstack22-llvm-606bc11367b475542bd6228163424ca43b4dbdbc
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
    save-always: false
  env:
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
Cache not found for input keys: openstack22-llvm-606bc11367b475542bd6228163424ca43b4dbdbc
```

**Comment by jedbrown** [comment]
Oh, caches have to be made on the same branch or the default branch. So this issue will go away as soon as we get a passing pipeline on `master`.
> The cache action first searches for cache hits for key and the cache version in the branch containing the workflow run. If there is no hit, it searches for restore-keys and the version. If there are still no hits in the current branch, the cache action retries same steps on the default branch. 
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key

**Comment by ZuseZ4** [comment]
@jedbrown Can you test this a bit? It should fix your thing and now also support slices.

**Comment by jedbrown** [comment]
Thanks, this is clean for me on two machines. I'll merge to `master` so we can seed that cache for future PRs.

**Pull request merged**
